name: Go Quality

on: [ push, pull_request ]

jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Check out code
        uses: actions/checkout@v4
      - name: Run Unit tests
        run: |
          go test -race -covermode=atomic -coverprofile=profile.cov -coverpkg=github.com/s7techlab/hlf-sdk-go/... ./client/...

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
